local module = require(script.Parent:FindFirstChild(".pesde"):FindFirstChild("ldgerrits_bootstrapper@1.2.2"):FindFirstChild("bootstrapper"))
export type LoadedModule  = module.LoadedModule 
export type LoadedModules  = module.LoadedModules 
export type ModulePath  = module.ModulePath 
export type Errors  = module.Errors 
export type PredicateFn  = module.PredicateFn 
export type Signal  = module.Signal 
export type Event  = module.Event 
export type Cleanup  = module.Cleanup 
export type Task  = module.Task 
return module